### ISSUE TITLE
[Feature request] Password protection

### ISSUE THREAD

**Issue by vatterspun** [hunterbeanland/AutoVer#1]
Ability to save to secure 7zip files that I can put on remote or attached storage.  In the case of cloud storage, I'd prefer if my provider didn't know what I was backing up and for my external drive.  For attached storage, I'd like to be protected in case someone walks off with said drive.

**Workaround**: save to a encrypted container folder like TrueCrypt or Veracrypt, which is a problem for cloud drives due to file size limitations.

**Comment by hunterbeanland** [comment]
included in the next version
