### ISSUE TITLE
[Feature request] Capability to break up zip or 7zip files

### ISSUE THREAD

**Issue by vatterspun** [hunterbeanland/AutoVer#4]
This is primarily for Cloud backup users that usually have a file backup size limit.  For example, Google Drive has a 50 meg file size limit (according to [this article](http://www.pcworld.com/article/2605912/onedrive-now-allows-files-of-up-to-10gb.html)).
 
## Current behavior

Files saved to the available archive (under the _Versioning_ tab of the _Watcher_ window) grow over time as files are versioned with no discernible limit.

## Requested behavior

Ability to break up individual ZIP or 7ZIP files into limited size files, For example, a 115 meg file would become six separate 20 meg files.

**Comment by hunterbeanland** [comment]
Google Drive max file size is about 12GB these days. Anyway, I am implementing a max size in the next version, otherwise the files grow to insane sizes
