### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by vatterspun** [hunterbeanland/AutoVer#9]
Just wanted to get someone to reply here as to whether or not the project is simply on hold or has shut down.

Whatever the case, this program still works great on both my Win7-86 and Win10-64 machines despite some minor issues (some detailed here on Github).  I love it, I've donated in the past, and would certainly donate in the future.

**Comment by hunterbeanland** [comment]
Not dead - just an extended rest. I don't have time to work on it. But i'd like to - I still use the program at work. Perhaps in a few months I'd like to at least clean up the issues.

**Comment by vatterspun** [comment]
> Not dead - just an extended rest. I don't have time to work on it. But i'd like to - I still use the program at work. Perhaps in a few months I'd like to at least clean up the issues.

I certainly understand that other things have priority.  Thanks for responding.

**Comment by vertigo220** [comment]
Just want to add that I completely understand time limitations, and if you can't do it you can't do it, but I also would like to say that AutoVer is the _only_ program I've been able to find, searching here and there for the past several years, that does what it does, so it would be great if you were able to keep working on it. I wouldn't doubt you could even make money off of licensing it if that's what it took. It basically does what Windows' File History _should_ do, and it could be so much better with some additional options and tweaks.
